//Types proyectos
export const FORMULARIO_PROYECTO = "FORMULARIO_PROYECTO",
    OBTENER_PROYECTOS = "OBTENER_PROYECTOS",
    AGREGAR_PROYECTO = "AGREGAR_PROYECTO",
    MOSTRAR_ERROR = "MOSTRAR_ERROR",
    SELECCIONAR_PROYECTO = "SELECCIONAR_PROYECTO",
    ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO",
    PROYECTO_ERROR = "PROYECTO_ERROR"

//Types tareas
export const
    OBTENER_TAREAS = "OBTENER_TAREAS",
    AGREGAR_TAREA = "AGREGAR_TAREA",
    VALIDAR_TAREA = "VALIDAR_TAREA",
    ELIMINAR_TAREA = "ELIMINAR_TAREA",
    SELECCIONAR_TAREA = "SELECCIONAR_TAREA",
    EDITAR_TAREA = "EDITAR_TAREA"

//Types alertas
export const
    MOSTRAR_ALERTA = "MOSTRAR_ALERTA",
    OCULTAR_ALERTA = "OCULTAR_ALERTA";

//Types autenticación
export const
    REGISTRO_EXITOSO = "REGISTRO_EXITOSO",
    REGISTRO_ERROR = "REGISTRO_ERROR",
    OBTENER_USUARIO = "OBTENER_USUARIO",
    LOGIN_EXITOSO = "LOGIN_EXITOSO",
    LOGIN_ERROR = "LOGIN_ERROR",
    CERRAR_SESION = "CERRAR_SESION"
